### ISSUE TITLE
Problemă instalare 

### ISSUE THREAD

**Issue by arcilli** [civictechro/auth-sso#39]
Am încercat să instalez portalul folosind https://github.com/civictechro/auth-sso/wiki/Tutorial. 
Am instalat gitul, Visual Studio-ul, .Net-ul și celelalte. Am făcut baza de date din php cu atribuirea userului pentru baza de date, am dat `<npm install bower -g>`  și `<npm install gulp -p>` , iar apoi am intrat în cmd, \auth-sso, am rulat `<git submodule update --init --recursive>`, iar apoi `<dotnet restore>`, moment in care am primit erori: 
```E:\CivicTech\auth-sso\src\GovITHub.Auth.Identity\GovITHub.Auth.Identity.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.App from 1.1.2 to 1.1.1. Reference the package directly from the project to select a different version. \r [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
E:\CivicTech\auth-sso\src\GovITHub.Auth.Identity\GovITHub.Auth.Identity.csproj : error NU1605:  GovITHub.Auth.Identity (>= 1.0.0) -> Localization.SqlLocalizer (>= 1.0.10) -> Microsoft.NETCore.App (>= 1.1.2) \r [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
E:\CivicTech\auth-sso\src\GovITHub.Auth.Identity\GovITHub.Auth.Identity.csproj : error NU1605:  GovITHub.Auth.Identity (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.1) [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
E:\CivicTech\auth-sso\src\GovITHub.Auth.Identity\GovITHub.Auth.Identity.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.App from 1.1.2 to 1.1.1. Reference the package directly from the project to select a different version. \r [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
E:\CivicTech\auth-sso\src\GovITHub.Auth.Identity\GovITHub.Auth.Identity.csproj : error NU1605:  GovITHub.Auth.Identity (>= 1.0.0) -> Microsoft.VisualStudio.Web.CodeGeneration.Design (>= 1.1.1) -> Microsoft.NETCore.App (>= 1.1.2) \r [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
E:\CivicTech\auth-sso\src\GovITHub.Auth.Identity\GovITHub.Auth.Identity.csproj : error NU1605:  GovITHub.Auth.Identity (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.1) [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
E:\CivicTech\auth-sso\src\GovITHub.Auth.Common\GovITHub.Auth.Common.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.App from 1.1.2 to 1.1.1. Reference the package directly from the project to select a different version. \r [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
E:\CivicTech\auth-sso\src\GovITHub.Auth.Common\GovITHub.Auth.Common.csproj : error NU1605:  GovITHub.Auth.Common (>= 1.0.0) -> Localization.SqlLocalizer (>= 1.0.10) -> Microsoft.NETCore.App (>= 1.1.2) \r [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
E:\CivicTech\auth-sso\src\GovITHub.Auth.Common\GovITHub.Auth.Common.csproj : error NU1605:  GovITHub.Auth.Common (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.1) [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]```

**Comment by alexchiraples** [comment]
Pare a fi o problema de versiune .net core `2.0 preview`. Eu am instalat local `1.0.4`, nu am facut inca trecerea la `2.0`.
Ce ouput primesti cand rulezi: `dotnet --version`?

**Comment by arcilli** [comment]
```E:\CivicTech\auth-sso\src\GovITHub.Auth.Identity>dotnet --version
2.0.0

**Comment by alexchiraples** [comment]
Temporar, pana cand facem upgrade-ul la `2.0`, instaleaza te rog o versiune mai veche:
https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.5-download.md

Daca primesti eroarea de mai sus:
1. uninstall `1.0.5`
2. uninstall `2.0`
3. install `1.0.5`

**Comment by arcilli** [comment]
``E:\CivicTech\auth-sso>dotnet --version
A fatal error occurred, the required library hostfxr.dll could not be found at C:\Program Files\dotnet``

**Comment by alexchiraples** [comment]
uninstall tot. install `1.0.5`

**Comment by tzapzoor** [comment]
@arcilli Pe mine m-a ajutat asta cu versiunea 2.0.0:
https://stackoverflow.com/questions/42709533/detected-package-downgrade-warning-dotnet-core-vs-2017

**Comment by arcilli** [comment]
L-am rezolvat dându-i repair. Acum la `dotnet run` primesc blank page cand dau sa accesez localhost:5000 și niște fail-uri la rulare dotnet.
```info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action GovITHub.Auth.Identity.Controllers.HomeController.Error (GovITHub.Auth.Identity) in 23.015ms
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An exception was thrown attempting to execute the error handler.
MySql.Data.MySqlClient.MySqlException: AuthenticationFailed ---> MySql.Data.MySqlClient.MySqlException: Access denied for user '<user>'@'localhost' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Localization.SqlLocalizer.DbStringLocalizer.SqlStringLocalizerFactory.GetAllFromDatabaseForResource(String resourceKey)
   at Localization.SqlLocalizer.DbStringLocalizer.SqlStringLocalizerFactory.Create(Type resourceSource)
   at Microsoft.Extensions.Localization.StringLocalizer`1..ctor(IStringLocalizerFactory factory)
   at lambda_method(Closure , ServiceProvider )
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.FederatedSignOutMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.AuthenticationMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
fail: Microsoft.AspNetCore.Server.Kestrel[13]```

**Comment by tzapzoor** [comment]
@arcilli ``Access denied for user '<user>'@'localhost' (using password: YES)`` - 

- in connectionsstrings.json ai setarile pt baza de date la inceput (search dupa ``<user>``)

**Comment by arcilli** [comment]
@tzapzoor, mersi. Le-am actualizat și am aceeași eroare, + că încă la `dotnet restore` primesc warningul cu versiunea de .NET 
```C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.NETCore.App from 1.1.2 to 1.1.1 \r [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  GovITHub.Auth.Common.Tests (>= 1.0.0) -> GovITHub.Auth.Common (>= 1.0.0) -> Localization.SqlLocalizer (>= 1.0.10) -> Microsoft.NETCore.App (>= 1.1.2) \r [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  GovITHub.Auth.Common.Tests (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.1) [E:\CivicTech\auth-sso\GovITHub.Auth.Identity.sln]```

**Comment by tzapzoor** [comment]
@arcilli in folderul ``test`` mai este un proiect care trebuie reparat si el la fel cum le-ai reparat pe celelalte. Daca nu merge aceeasi solutie pe care ai folosit-o, poti incerca link-ul pe care l-am pus mai sus.

**Comment by arcilli** [comment]
@tzapzoor, i-am șters liniile alea din fiecare proiect. La `dotnet run` intră-n buclă infinită și la final
```Using launch settings from E:\GovITHub\auth-sso\src\GovITHub.Auth.Identity\Properties\launchSettings.json...

Unhandled Exception: System.Exception: Could not resolve a service of type 'GovITHub.Auth.Common.Data.ConfigurationDataInitializer' for the parameter 'cfgDataInitializer' of method 'Configure' on type 'GovITHub.Auth.Identity.Startup'. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalOptionsExtension.set_ConnectionString(String value)
   at MySQL.Data.Entity.Extensions.MySQLDbContextOptionsExtensions.UseMySQL(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 mysqlOptionsAction)
   at GovITHub.Auth.Identity.Startup.<>c__DisplayClass4_0.<ConfigureServices>b__4(DbContextOptionsBuilder builder) in E:\GovITHub\auth-sso\src\GovITHub.Auth.Identity\Startup.cs:line 102
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.DbContextOptionsFactory[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at GovITHub.Auth.Identity.Program.Main(String[] args) in E:\GovITHub\auth-sso\src\GovITHub.Auth.Identity\Program.cs:line 10
```
